name: API Tests - Dog API + Allure

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "maven"

      - name: Run tests + generate Allure report
        run: mvn -B -ntp clean test verify -Ddog.api.env=dev

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

